gbm_lgm = {
    "boosting_type": "gbdt",
    "class_weight": None,
    "colsample_bytree": 1.0,
    "importance_type": "split",
    "learning_rate": 0.1,
    "max_depth": -1,
    "min_child_samples": 20,
    "min_child_weight": 0.001,
    "min_split_gain": 0.0,
    "n_estimators": 483,
    "n_jobs": -1,
    "num_leaves": 31,
    "objective": "binary",
    "random_state": None,
    "reg_alpha": 0.0,
    "reg_lambda": 0.0,
    "silent": True,
    "subsample": 1.0,
    "subsample_for_bin": 200000,
    "subsample_freq": 0,
    "metric": "binary",
    "bagging_fraction": 0.5,
    "is_unbalance": True,
}

entropy_tree = {
    "ccp_alpha": 0.0,
    "class_weight": "balanced",
    "criterion": "entropy",
    "max_depth": 90,
    "max_features": "auto",
    "max_leaf_nodes": None,
    "min_impurity_decrease": 0.0,
    "min_impurity_split": None,
    "min_samples_leaf": 1,
    "min_samples_split": 7,
    "min_weight_fraction_leaf": 0.0,
    "presort": "deprecated",
    "random_state": None,
    "splitter": "best",
}

gini_tree = {
    "ccp_alpha": 0.0,
    "class_weight": "balanced",
    "criterion": "gini",
    "max_depth": None,
    "max_features": "auto",
    "max_leaf_nodes": None,
    "min_impurity_decrease": 0.0,
    "min_impurity_split": None,
    "min_samples_leaf": 4,
    "min_samples_split": 10,
    "min_weight_fraction_leaf": 0.0,
    "presort": "deprecated",
    "random_state": None,
    "splitter": "best",
}
